### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by AlonHor** [K9Developer/Assembly-Graphics-API#2]
In the README file:
> I started learning ASM about 6 months ago, so if you have any notes **_please leave then_** in the [issues page](https://github.com/K9Developer/Assembly-Graphics-API/issues)

Should be "_please leave **them**_".

**Comment by K9Developer** [comment]
> In the README file:
> > I started learning ASM about 6 months ago, so if you have any notes **_please leave then_** in the [issues page](https://github.com/K9Developer/Assembly-Graphics-API/issues)
> 
> Should be "_please leave **them**_".

Please open a PR request fixing this, and while your'e at it please update the api docs! Thank you 😊 

For anyone seeing this i know him irl, this is a joke lol
